apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service-a
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /service-a
spec:
  rules:
    - http:
        paths:
        - path: /service-a
          backend:
            serviceName: service-a
            servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service-b
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
        - path: /service-b
          backend:
            serviceName: service-b
            servicePort: 80



